# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\vpoly\qt\game\crisscross.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gameButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.gameButton_0.setMinimumSize(QtCore.QSize(170, 170))
        self.gameButton_0.setMaximumSize(QtCore.QSize(170, 170))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.gameButton_0.setFont(font)
        self.gameButton_0.setText("")
        self.gameButton_0.setObjectName("gameButton_0")
        self.horizontalLayout.addWidget(self.gameButton_0)
        self.gameButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.gameButton_1.setMinimumSize(QtCore.QSize(170, 170))
        self.gameButton_1.setMaximumSize(QtCore.QSize(170, 170))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.gameButton_1.setFont(font)
        self.gameButton_1.setText("")
        self.gameButton_1.setObjectName("gameButton_1")
        self.horizontalLayout.addWidget(self.gameButton_1)
        self.gameButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.gameButton_2.setMinimumSize(QtCore.QSize(170, 170))
        self.gameButton_2.setMaximumSize(QtCore.QSize(170, 170))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.gameButton_2.setFont(font)
        self.gameButton_2.setText("")
        self.gameButton_2.setObjectName("gameButton_2")
        self.horizontalLayout.addWidget(self.gameButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gameButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.gameButton_3.setMinimumSize(QtCore.QSize(170, 170))
        self.gameButton_3.setMaximumSize(QtCore.QSize(170, 170))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.gameButton_3.setFont(font)
        self.gameButton_3.setText("")
        self.gameButton_3.setObjectName("gameButton_3")
        self.horizontalLayout_2.addWidget(self.gameButton_3)
        self.gameButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.gameButton_4.setMinimumSize(QtCore.QSize(170, 170))
        self.gameButton_4.setMaximumSize(QtCore.QSize(170, 170))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.gameButton_4.setFont(font)
        self.gameButton_4.setText("")
        self.gameButton_4.setObjectName("gameButton_4")
        self.horizontalLayout_2.addWidget(self.gameButton_4)
        self.gameButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.gameButton_5.setMinimumSize(QtCore.QSize(170, 170))
        self.gameButton_5.setMaximumSize(QtCore.QSize(170, 170))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.gameButton_5.setFont(font)
        self.gameButton_5.setText("")
        self.gameButton_5.setObjectName("gameButton_5")
        self.horizontalLayout_2.addWidget(self.gameButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gameButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.gameButton_6.setMinimumSize(QtCore.QSize(170, 170))
        self.gameButton_6.setMaximumSize(QtCore.QSize(170, 170))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.gameButton_6.setFont(font)
        self.gameButton_6.setText("")
        self.gameButton_6.setObjectName("gameButton_6")
        self.horizontalLayout_3.addWidget(self.gameButton_6)
        self.gameButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.gameButton_7.setMinimumSize(QtCore.QSize(170, 170))
        self.gameButton_7.setMaximumSize(QtCore.QSize(170, 170))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.gameButton_7.setFont(font)
        self.gameButton_7.setText("")
        self.gameButton_7.setObjectName("gameButton_7")
        self.horizontalLayout_3.addWidget(self.gameButton_7)
        self.gameButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.gameButton_8.setMinimumSize(QtCore.QSize(170, 170))
        self.gameButton_8.setMaximumSize(QtCore.QSize(170, 170))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.gameButton_8.setFont(font)
        self.gameButton_8.setText("")
        self.gameButton_8.setObjectName("gameButton_8")
        self.horizontalLayout_3.addWidget(self.gameButton_8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.newGameButton = QtWidgets.QPushButton(self.centralwidget)
        self.newGameButton.setMinimumSize(QtCore.QSize(0, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.newGameButton.setFont(font)
        self.newGameButton.setObjectName("newGameButton")
        self.verticalLayout.addWidget(self.newGameButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.newGameButton.setText(_translate("MainWindow", "New Game"))
